### ISSUE TITLE
len(string) or string.len

### ISSUE THREAD

**Issue by loloiccl** [2vg/Nim-World#2]
chapter2-3.md において string.len という形の表記と len(string) の形の表記が混在している．
まだ Nim のメソッドチェイン的記法について説明していないため，統一したい．

どちらに統一すべきでしょう?

**Comment by 2vg** [comment]
記法は正直何でもいいんじゃないかな(適当

実は書き方2種だけじゃなくて`len str`, `len(str)`, `str.len`, `str.len`などなど色んな書き方があるのでなんとも言えないんですよね…

len(str)が直感的に分かりやすいかなぁと(私が

**Comment by loloiccl** [comment]
結局 len が使われない方向に向きそうなので close.
